docs_dir: mkdocs
site_name: Safely Report
repo_name: princeton-ddss/safely-report
repo_url: https://github.com/princeton-ddss/safely-report
copyright: Copyright &copy; 2023-2024 The Trustees of Princeton University

theme:
  name: material
  # logo: images/logo.png
  # favicon: images/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - tables
  - toc:
      permalink: true

plugins:
  - search

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Concepts:
    - Garbling: concepts/garbling.md
  - Guides:
    - Creating Survey Files: guides/create-survey-files.md
    - Deploying App: guides/deploy-app.md
    - Analyzing Results: guides/analyze-results.md
