name: Python application

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-mock pytest-dotenv
          pip install ruff mypy

      - name: Run testing
        run: |
          source venv/bin/activate
          pytest tests

      - name: Run linting and formatting
        run: |
          source venv/bin/activate
          ruff check .
          ruff format .

      - name: Run type checking
        run: |
          source venv/bin/activate
          mypy --ignore-missing-imports .
